// Code generated by protoc-gen-go.
// source: sample.proto
// DO NOT EDIT!

/*
Package sample is a generated protocol buffer package.

It is generated from these files:
	sample.proto

It has these top-level messages:
	Test
	SampleReq
	SampleResp
*/
package sample

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Test struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Test) Reset()                    { *m = Test{} }
func (m *Test) String() string            { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()               {}
func (*Test) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SampleReq struct {
	Go bool `protobuf:"varint,1,opt,name=go" json:"go,omitempty"`
}

func (m *SampleReq) Reset()                    { *m = SampleReq{} }
func (m *SampleReq) String() string            { return proto.CompactTextString(m) }
func (*SampleReq) ProtoMessage()               {}
func (*SampleReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SampleResp struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
}

func (m *SampleResp) Reset()                    { *m = SampleResp{} }
func (m *SampleResp) String() string            { return proto.CompactTextString(m) }
func (*SampleResp) ProtoMessage()               {}
func (*SampleResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Test)(nil), "Test")
	proto.RegisterType((*SampleReq)(nil), "SampleReq")
	proto.RegisterType((*SampleResp)(nil), "SampleResp")
}

func init() { proto.RegisterFile("sample.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0xcc, 0x2d,
	0xc8, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x92, 0xe2, 0x62, 0x09, 0x49, 0x2d, 0x2e,
	0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02,
	0xb3, 0x95, 0xa4, 0xb9, 0x38, 0x83, 0xc1, 0x6a, 0x83, 0x52, 0x0b, 0x85, 0xf8, 0xb8, 0x98, 0xd2,
	0xf3, 0xc1, 0xd2, 0x1c, 0x41, 0x40, 0x96, 0x92, 0x02, 0x17, 0x17, 0x4c, 0xb2, 0xb8, 0x00, 0xa4,
	0xbd, 0x24, 0xb5, 0xa2, 0x04, 0xa6, 0x1d, 0xc4, 0x4e, 0x62, 0x03, 0xdb, 0x60, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x7f, 0x53, 0x87, 0xb0, 0x71, 0x00, 0x00, 0x00,
}
